// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UIWindow;
@class UIApplication;

SWIFT_CLASS("_TtC13FTCoreUtility13FTAppDelegate")
@interface FTAppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (BOOL)application:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
- (void)applicationWillResignActive:(UIApplication * _Nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * _Nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * _Nonnull)application;
- (void)applicationDidBecomeActive:(UIApplication * _Nonnull)application;
- (void)applicationWillTerminate:(UIApplication * _Nonnull)application;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;
@class UIColor;

SWIFT_PROTOCOL("_TtP13FTCoreUtility15FTThemeProtocol_")
@protocol FTThemeProtocol
- (NSString * _Nullable)get_ThemeSubType SWIFT_WARN_UNUSED_RESULT;
@optional
- (void)updateTheme:(NSDictionary<NSString *, id> * _Nonnull)theme;
- (void)theme_isLinkUnderlineEnabled:(BOOL)bool_;
- (void)theme_isLinkDetectionEnabled:(BOOL)bool_;
- (void)theme_textfont:(UIFont * _Nonnull)font;
- (void)theme_textcolor:(UIColor * _Nonnull)color;
- (void)theme_backgroundColor:(UIColor * _Nonnull)color;
@end

@class NSCoder;

SWIFT_CLASS("_TtC13FTCoreUtility10FTUIButton")
@interface FTUIButton : UIButton <FTThemeProtocol>
- (NSString * _Nullable)get_ThemeSubType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13FTCoreUtility24FTUIControlThemeProtocol_")
@protocol FTUIControlThemeProtocol
@optional
- (BOOL)get_AllThemeSubType SWIFT_WARN_UNUSED_RESULT;
- (void)setThemes:(NSDictionary<NSString *, id> * _Nonnull)themes;
- (void)updateWithThemeDic:(NSDictionary<NSString *, id> * _Nonnull)themeDic state:(UIControlState)state;
@end


@interface FTUIButton (SWIFT_EXTENSION(FTCoreUtility)) <FTUIControlThemeProtocol>
- (void)updateWithThemeDic:(NSDictionary<NSString *, id> * _Nonnull)themeDic state:(UIControlState)state;
@end



SWIFT_CLASS("_TtC13FTCoreUtility9FTUILabel")
@interface FTUILabel : UILabel <FTThemeProtocol>
- (void)updateTheme:(NSDictionary<NSString *, id> * _Nonnull)theme;
- (NSString * _Nullable)get_ThemeSubType SWIFT_WARN_UNUSED_RESULT;
- (void)theme_isLinkUnderlineEnabled:(BOOL)bool_;
- (void)theme_isLinkDetectionEnabled:(BOOL)bool_;
- (void)theme_textfont:(UIFont * _Nonnull)font;
- (void)theme_textcolor:(UIColor * _Nonnull)color;
- (void)theme_backgroundColor:(UIColor * _Nonnull)color;
- (void)updateVisualThemes;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FTCoreUtility10FTUITabBar")
@interface FTUITabBar : UITabBar <FTThemeProtocol>
- (void)updateTheme:(NSDictionary<NSString *, id> * _Nonnull)theme;
- (NSString * _Nullable)get_ThemeSubType SWIFT_WARN_UNUSED_RESULT;
- (void)theme_backgroundColor:(UIColor * _Nonnull)color;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FTCoreUtility8FTUIView")
@interface FTUIView : UIView <FTThemeProtocol>
- (NSString * _Nullable)get_ThemeSubType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

@interface UIColor (SWIFT_EXTENSION(FTCoreUtility))
- (nonnull instancetype)initWithRgb:(uint32_t)rgb a:(CGFloat)a;
- (nonnull instancetype)initWithRgba:(uint32_t)rgba;
+ (UIColor * _Nullable)hexColor:(NSString * _Nonnull)hex SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nonnull)generateImageWithOpacity:(CGFloat)opacity contextSize:(CGSize)contextSize contentsScale:(CGFloat)contentsScale SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)hexColor SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIControl (SWIFT_EXTENSION(FTCoreUtility))
- (BOOL)get_AllThemeSubType SWIFT_WARN_UNUSED_RESULT;
- (void)setThemes:(NSDictionary<NSString *, id> * _Nonnull)themes;
@end


@interface UIImage (SWIFT_EXTENSION(FTCoreUtility))
- (UIColor * _Nullable)getColorAtPoint:(CGPoint)atPoint a:(CGFloat)a SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIImageView (SWIFT_EXTENSION(FTCoreUtility))
- (void)downloadedFromUrl:(NSURL * _Nonnull)url contentMode:(UIViewContentMode)mode;
- (void)downloadedFromLink:(NSString * _Nonnull)link contentMode:(UIViewContentMode)mode;
@end

@class UINib;

@interface UIView (SWIFT_EXTENSION(FTCoreUtility))
+ (UIView * _Nonnull)embedViewWithContentView:(UIView * _Nonnull)contentView SWIFT_WARN_UNUSED_RESULT;
- (void)removeSubviews;
+ (UINib * _Nullable)getNIBFile SWIFT_WARN_UNUSED_RESULT;
+ (UIView * _Nullable)fromNibWithNamed:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
+ (UIView * _Nullable)fromNib SWIFT_WARN_UNUSED_RESULT;
- (void)removeAllConstraints;
- (NSArray<UIImageView *> * _Nullable)findShadowImage SWIFT_WARN_UNUSED_RESULT;
- (void)hideShadowImage;
@end


@interface UIView (SWIFT_EXTENSION(FTCoreUtility))
@end


@interface UIView (SWIFT_EXTENSION(FTCoreUtility))
@property (nonatomic, copy) NSString * _Nullable theme;
@property (nonatomic) BOOL needsThemesUpdate;
@end


@interface UIView (SWIFT_EXTENSION(FTCoreUtility))
- (void)addSizeConstraint:(CGFloat)width :(CGFloat)height;
- (void)addSelfSizing;
- (void)resizeToFitSubviewsInScreen;
- (void)resizeToFitSubviews;
- (void)setViewSize:(CGSize)size createConstraint:(BOOL)createConstraint relation:(NSLayoutRelation)relation;
- (void)setViewHeight:(CGFloat)height createConstraint:(BOOL)createConstraint relation:(NSLayoutRelation)relation;
- (void)setViewWidth:(CGFloat)width createConstraint:(BOOL)createConstraint relation:(NSLayoutRelation)relation;
@end

#pragma clang diagnostic pop
